# A02

# Data Manipulation for Modeling

|                |   |
:----------------|---|
| **Nombre**     |María Fernanda Muñoz Sevilla   |
| **Fecha**     |01/09/2025  |
| **Expediente**  |751190  |

In [62]:
import pandas as pd
import statsmodels.api as sm
from sklearn.linear_model import LinearRegression
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import r2_score

In [64]:
df= pd.read_excel("C:/Users/munoz/Downloads/lab_apre_est/Boston Housing Dataset 1978.xlsx")
df.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2

In [66]:
df.head(n=5)#muestra las primeras 5

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2

In [68]:
df.tail(n=5)#muestra las ultimas 5

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
501,0.06263,0.0,11.93,0.0,0.573,6.593,69.1,2.4786,1,273.0,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0.0,0.573,6.120,76.7,2.2875,1,273.0,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0.0,0.573,6.976,91.0,2.1675,1,273.0,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0.0,0.573,6.794,89.3,2.3889,1,273.0,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0.0,0.573,6.030,80.8,2.5050,1,273.0,21.0,396.90,7.88,11.9

In [72]:
df2= df.dropna()
df2

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0.0,0.573,6.593,69.1,2.4786,1,273.0,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0.0,0.573,6.120,76.7,2.2875,1,273.0,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0.0,0.573,6.976,91.0,2.1675,1,273.0,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0.0,0.573,6.794,89.3,2.3889,1,273.0,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0.0,0.573,6.030,80.8,2.5050,1,273.0,21.0,396.90,7.88,11.9

In [74]:
df2.drop_duplicates()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0.0,0.573,6.593,69.1,2.4786,1,273.0,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0.0,0.573,6.120,76.7,2.2875,1,273.0,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0.0,0.573,6.976,91.0,2.1675,1,273.0,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0.0,0.573,6.794,89.3,2.3889,1,273.0,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0.0,0.573,6.030,80.8,2.5050,1,273.0,21.0,396.90,7.88,11.9

In [78]:
df.describe()#describe nuestro dataset

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
count,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,452.000000
mean,1.269195,13.295257,9.205158,0.140765,1.101175,15.679800,58.744660,6.173308,78.063241,339.317787,42.614980,332.791107,11.537806,23.750442
std,2.399207,23.048697,7.169630,0.312765,1.646991,27.220206,33.104049,6.476435,203.542157,180.670077,87.585243,125.322456,6.064932,8.808602
min,0.000000,0.000000,0.000000,0.000000,0.385000,3.561000,1.137000,1.129600,1.000000,20.200000,2.600000,0.320000,1.730000,6.300000
25%,0.049443,0.000000,3.440000,0.000000,0.449000,5.961500,32.000000,2.430575,4.000000,254.000000,17.000000,364.995000,6.877500,18.500000
50%,0.144655,0.000000,6.960000,0.000000,0.538000,6.322500,65.250000,3.925850,5.000000,307.000000,18.900000,390.660000,10.380000,21.950000
75%,0.819623,18.100000,18.100000,0.000000,0.647000,6.949000,89.975000,6.332075,24.000000,403.000000,20.200000,395.615000,15.015000,26.600000
max,9.966540,100.000000,27.740000,1.000000,7.313000,100.000000,100.000000,24.000000,666.000000,711.000000,396.900000,396.900000,34.410000,50.000000

In [98]:
x1=df2.CRIM.values.reshape([-1,1])
x2=df2.ZN.values.reshape([-1,1])
x3=df2.INDUS.values.reshape([-1,1])
x4=df2.CHAS.values.reshape([-1,1])
x5=df2.NOX.values.reshape([-1,1])
x6=df2.RM.values.reshape([-1,1])
x7=df2.AGE.values.reshape([-1,1])
x8=df2.DIS.values.reshape([-1,1])
x9=df2.RAD.values.reshape([-1,1])
x10=df2.TAX.values.reshape([-1,1])
x11=df2.PTRATIO.values.reshape([-1,1])
x12=df2.B.values.reshape([-1,1])
x13=df2.LSTAT.values.reshape([-1,1])
y1=df2.MEDV
n1=len(y1)
unos=np.ones([n1,1])
X=np.hstack([unos,x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,x11,x12,x13])
ols=sm.OLS(y1,X)
resultados=ols.fit()
resultados.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                   MEDV   R-squared:                       0.741
Model:                            OLS   Adj. R-squared:                  0.733
Method:                 Least Squares   F-statistic:                     96.16
Date:                Mon, 01 Sep 2025   Prob (F-statistic):          2.64e-119
Time:                        17:29:42   Log-Likelihood:                -1319.4
No. Observations:                 452   AIC:                             2667.
Df Residuals:                     438   BIC:                             2724.
Df Model:                          13
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         20.8664      5.477      3.810      0.000      10.102      31.631
x1            -0.2380      0.224     -1.063      0.288      -0.678       0.202
x2             0.0382      0.013      2.858      0.004       0.012       0.065
x3             0.0514      0.060      0.861      0.390      -0.066       0.169
x4             2.4350      0.830      2.935      0.004       0.804       4.066
x5           -11.6580      3.928     -2.968      0.003     -19.378      -3.938
x6             5.1102      0.455     11.235      0.000       4.216       6.004
x7            -0.0061      0.013     -0.465      0.642      -0.032       0.020
x8            -1.2715      0.196     -6.495      0.000      -1.656      -0.887
x9             0.2944      0.085      3.448      0.001       0.127       0.462
x10           -0.0114      0.004     -3.145      0.002      -0.018      -0.004
x11           -0.8310      0.127     -6.544      0.000      -1.081      -0.581
x12            0.0123      0.004      3.505      0.001       0.005       0.019
x13           -0.5208      0.057     -9.068      0.000      -0.634      -0.408
==============================================================================
Omnibus:                      203.769   Durbin-Watson:                   1.181
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             1595.387
Skew:                           1.762   Prob(JB):                         0.00
Kurtosis:                      11.502   Cond. No.                     1.55e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.55e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [134]:
#CRIM
es1 = (x1 - np.min(x1)) / (np.max(x1 - np.min(x1)))
print("CRIM")
print("Min: ", es1.min(), "Max: ", es1.max())

CRIM
Min:  0.0 Max:  1.0

In [132]:
for col in df2.columns:
    if col=="MEDV" :
        break
    #Paso 1
    minval=df2[col].min()
    maxval=df2[col].max()
    #Paso 2
    aux=(df2[col]-minval)/(maxval-minval)
    df2[col]=aux
df2.describe()

C:\Users\munoz\AppData\Local\Temp\ipykernel_4480\2572872278.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2[col]=aux

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
count,452.000000,452.000000,452.000000,452.000000,452.000000,452.000000,452.000000,452.000000,452.000000,452.000000,452.000000,452.000000,452.000000,452.000000
mean,0.142015,0.127212,0.360883,0.077434,0.320608,0.533155,0.645293,0.264981,0.296653,0.363440,0.600758,0.931733,0.297181,23.750442
std,0.250586,0.243260,0.249161,0.267574,0.234189,0.127765,0.289671,0.190098,0.327978,0.288793,0.234049,0.172864,0.188385,8.808602
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.300000
25%,0.006381,0.000000,0.163856,0.000000,0.127572,0.453296,0.391864,0.111409,0.130435,0.171279,0.446809,0.951630,0.148638,18.500000
50%,0.018545,0.000000,0.281525,0.000000,0.275720,0.511209,0.709578,0.220135,0.173913,0.229008,0.638298,0.987846,0.260710,21.950000
75%,0.120995,0.200000,0.646628,0.000000,0.452675,0.589002,0.913749,0.388428,0.260870,0.427481,0.808511,0.998128,0.409272,26.600000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,50.000000

In [136]:
#MEDV
es2 = (y1 - np.min(y1)) / (np.max(y1 - np.min(y1)))
print("MEDV")
print("Min: ", es2.min(), "Max: ", es2.max())

MEDV
Min:  0.0 Max:  1.0

In [138]:
x1=df2.CRIM.values.reshape([-1,1])
x2=df2.ZN.values.reshape([-1,1])
x3=df2.INDUS.values.reshape([-1,1])
x4=df2.CHAS.values.reshape([-1,1])
x5=df2.NOX.values.reshape([-1,1])
x6=df2.RM.values.reshape([-1,1])
x7=df2.AGE.values.reshape([-1,1])
x8=df2.DIS.values.reshape([-1,1])
x9=df2.RAD.values.reshape([-1,1])
x10=df2.TAX.values.reshape([-1,1])
x11=df2.PTRATIO.values.reshape([-1,1])
x12=df2.B.values.reshape([-1,1])
x13=df2.LSTAT.values.reshape([-1,1])
y1=df2.MEDV
n1=len(y1)
unos=np.ones([n1,1])
X=np.hstack([unos,x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,x11,x12,x13])
ols=sm.OLS(y1,X)
resultados=ols.fit()
resultados.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                   MEDV   R-squared:                       0.741
Model:                            OLS   Adj. R-squared:                  0.733
Method:                 Least Squares   F-statistic:                     96.16
Date:                Mon, 01 Sep 2025   Prob (F-statistic):          2.64e-119
Time:                        17:50:08   Log-Likelihood:                -1319.4
No. Observations:                 452   AIC:                             2667.
Df Residuals:                     438   BIC:                             2724.
Df Model:                          13
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         19.9457      2.615      7.626      0.000      14.805      25.086
x1            -2.3708      2.230     -1.063      0.288      -6.753       2.011
x2             3.8221      1.337      2.858      0.004       1.194       6.450
x3             1.4010      1.627      0.861      0.390      -1.797       4.599
x4             2.4350      0.830      2.935      0.004       0.804       4.066
x5            -5.6658      1.909     -2.968      0.003      -9.418      -1.914
x6            26.6699      2.374     11.235      0.000      22.004      31.335
x7            -0.5917      1.272     -0.465      0.642      -3.092       1.908
x8           -13.9827      2.153     -6.495      0.000     -18.214      -9.752
x9             6.7722      1.964      3.448      0.001       2.912      10.632
x10           -5.9525      1.893     -3.145      0.002      -9.673      -2.232
x11           -7.8117      1.194     -6.544      0.000     -10.158      -5.465
x12            4.8836      1.393      3.505      0.001       2.145       7.622
x13          -17.0182      1.877     -9.068      0.000     -20.707     -13.330
==============================================================================
Omnibus:                      203.769   Durbin-Watson:                   1.181
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             1595.387
Skew:                           1.762   Prob(JB):                         0.00
Kurtosis:                      11.502   Cond. No.                         32.3
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""